apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-postgres
  namespace: postgres
spec:
  hard:
    requests.cpu: "4"
    requests.memory: 4Gi
    limits.cpu: "8"
    limits.memory: 8Gi
    pods: "20"
    persistentvolumeclaims: "5"
    services: "10"
