apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: integration
  name: integration-pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
