apiVersion: batch/v1
kind: CronJob
metadata:
  name: backup-postgres
  namespace: postgres
spec:
  schedule: "0 2 * * *"
  concurrencyPolicy: Forbid
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      template:
        spec:
          restartPolicy: OnFailure
          containers:
            - name: backup
              image: postgres:latest
              command: ["pg_dump", "-h", "postgresdb", "-U", "testuser", "testdb"]
              envFrom:
                - secretRef:
                    name: db-credentials
