apiVersion: v1
kind: Pod
metadata:
  name: webapp
  namespace: postgres
spec:
  initContainers:
    - name: wait-for-db
      image: busybox:latest
      command:
        - sh
        - -c
        - |
          until nc -z postgresdb 5432; do
            echo "Waiting for PostgreSQL..."
            sleep 2
          done
          echo "PostgreSQL is ready!"
  containers:
    - name: webapp
      image: nginx:latest
      ports:
        - containerPort: 8080
