apiVersion: v1
kind: Service
metadata:
  name: postgresdb-headless
  namespace: postgres
spec:
  clusterIP: None
  selector:
    app: postgresdb-sts
  ports:
    - port: 5432
      targetPort: 5432

---

apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgresdb-sts
  namespace: postgres
spec:
  serviceName: postgresdb-headless
  replicas: 3
  selector:
    matchLabels:
      app: postgresdb-sts
  template:
    metadata:
      labels:
        app: postgresdb-sts
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          envFrom:
            - secretRef:
                name: db-credentials
          volumeMounts:
            - name: data
              mountPath: /var/lib/postgresql
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        storageClassName: standard
        accessModes: [ReadWriteOnce]
        resources:
          requests:
            storage: 8Gi
