apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv
  labels:
    type: local
    app: postgresdb
spec:
  storageClassName: standard # Cette classe est utilisée par Docker,
                             # nous pourrions en utiliser une autre.
  capacity:
    storage: 8Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/data/db"