apiVersion: v1
kind: ConfigMap
metadata:
  namespace: postgres
  name: credentials
  labels:
    app: postgresdb
data:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword
