apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresdb
  namespace: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresdb
  template:
    metadata:
      labels:
        app: postgresdb
    spec:
      containers:
        - name: postgresdb
          image: postgres:latest
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: secret-volume
              mountPath: /etc/secrets
              readOnly: true
            - name: db-data
              mountPath: /var/lib/postgresql
      volumes:
        - name: secret-volume
          secret:
            secretName: db-credentials
        - name: db-data
          persistentVolumeClaim:
            claimName: pvc
