apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: postgres
  name: pvc
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 8Gi
