replicaCount: 1

image:
  repository: postgres
  tag: "16"
  pullPolicy: IfNotPresent

env:
  POSTGRES_DB: testdb
  POSTGRES_USER: testuser
  POSTGRES_PASSWORD: testpassword

service:
  type: ClusterIP
  port: 5432

storage:
  storageClass: standard
  size: 8Gi
  mountPath: /var/lib/postgresql

resources:
  limits:
    cpu: 500m
    memory: 512Mi
  requests:
    cpu: 250m
    memory: 256Mi
